version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    volumes:
      - ./.logs:/var/log
      - ./.data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200
